CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    last_location TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);